// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWSEqM5rmL-E7YEhjN1aUTFX9QBS8QEb4',
    appId: '1:329402518069:web:77225c33b06877172f7f7c',
    messagingSenderId: '329402518069',
    projectId: 'virtual-wallet-app-a7688',
    authDomain: 'virtual-wallet-app-a7688.firebaseapp.com',
    storageBucket: 'virtual-wallet-app-a7688.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVBGCUOT626cmZVlozBdGXyoYmXqAuuU',
    appId: '1:329402518069:android:c3f0ba15a9be430b2f7f7c',
    messagingSenderId: '329402518069',
    projectId: 'virtual-wallet-app-a7688',
    storageBucket: 'virtual-wallet-app-a7688.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWZZWLc44cLRFRsvXjEvo6zhuRMCKEIoY',
    appId: '1:329402518069:ios:f6651ec82690b9ca2f7f7c',
    messagingSenderId: '329402518069',
    projectId: 'virtual-wallet-app-a7688',
    storageBucket: 'virtual-wallet-app-a7688.firebasestorage.app',
    iosBundleId: 'com.example.virutalWallet',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWZZWLc44cLRFRsvXjEvo6zhuRMCKEIoY',
    appId: '1:329402518069:ios:f6651ec82690b9ca2f7f7c',
    messagingSenderId: '329402518069',
    projectId: 'virtual-wallet-app-a7688',
    storageBucket: 'virtual-wallet-app-a7688.firebasestorage.app',
    iosBundleId: 'com.example.virutalWallet',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWSEqM5rmL-E7YEhjN1aUTFX9QBS8QEb4',
    appId: '1:329402518069:web:db300404aeef46012f7f7c',
    messagingSenderId: '329402518069',
    projectId: 'virtual-wallet-app-a7688',
    authDomain: 'virtual-wallet-app-a7688.firebaseapp.com',
    storageBucket: 'virtual-wallet-app-a7688.firebasestorage.app',
  );
}
